### ISSUE TITLE
Audio stream not heard and other models not compatible

### ISSUE THREAD

**Issue by MathisFederico** [yinkalario/General-Purpose-Sound-Recognition-Demo#1]
Hi !

I tried to replicate but even if the GUI window opens and predictions are done, it just predict silence as if the audio stream wasn't heard by the algorithm ... I would very much like to continue your work, do you think that could be done ?

Also, I tried using other models pretrained on https://github.com/qiuqiangkong/audioset_tagging_cnn but I'm getting shape mismatches ...

**Comment by yinkalario** [comment]
Hi there,

If your audio stream doesn't work, you need to check if your pyaudio or pysound models are imported and running correctly. We didn't test this on a lot of computers. 

Sorry for the misleading. Yes, the model used in this repo is a little bit different than the model on  https://github.com/qiuqiangkong/audioset_tagging_cnn. But not a lot. So there will be some errors directly using the model from another repo.

You could also try this demo: https://github.com/yinkalario/Sound-Event-Detection-AudioSet. This demo uses exactly the same model in https://github.com/qiuqiangkong/audioset_tagging_cnn.

Thanks

**Comment by MathisFederico** [comment]
Hi !

Thank you very much for your answer !
The audio stream was a mistake on my part indeed ! Sorry about that !

I will try the other demo thanks !
