### ISSUE TITLE
Size mismatch

### ISSUE THREAD

**Issue by nhenrys** [yinkalario/General-Purpose-Sound-Recognition-Demo#3]
Hello, I'm trying to adapt this to use with the Wavegram_Logmel_Cnn14_mAP=0.439 model. 

However I get a size mismatch error:

"size mismatch for conv_block2.conv1.weight: copying a param with shape torch.Size([128, 128, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 64, 3, 3])"

what do I need to change to make this work?

**Comment by yinkalario** [comment]
The model "Wavegram_Logmel_Cnn14_mAP=0.439" is slightly different than the one shared in this repo. If you really want to use "Wavegram_Logmel_Cnn14_mAP=0.439", you need to adapt the code in ./models_code/models.py to the code in https://github.com/qiuqiangkong/audioset_tagging_cnn/blob/master/pytorch/models.py

Thanks
