### ISSUE TITLE
How to change pretrained model?

### ISSUE THREAD

**Issue by rhiver** [yinkalario/General-Purpose-Sound-Recognition-Demo#8]
In README, you mentioned some pretrained models:
'More models can be found [here](https://zenodo.org/record/3576599) and [here](https://zenodo.org/record/3987831).'

I tried to use models from the latter url: https://zenodo.org/record/3987831.
But I found that I could not run the demo by simply changing the MODEL_PATH to another model.

Then I tried to add some model definitions from https://github.com/qiuqiangkong/audioset_tagging_cnn/blob/master/pytorch/models.py to sed_demo/models.py, and changed the model in class DemoApp like: 'self.model = Cnn10(samplerate, model_winsize, stft_hopsize, n_mels, mel_fmin, mel_fmax, num_audioset_classes)'
But I still got errors like: 'AssertionError: 4D tensors expect 4 values for padding'.

I am stuck here. Any suggestions?

**Comment by andres-fr** [comment]
Hi @rhiver, sorry for the delayed answer.

The mention in the README is intended as a pointer, but the demo doesn't support plug-and-play model swapping.
You would have to add the corresponding model to the codebase (e.g. to `models.py`), and then adapt the inference correspondingly (e.g. in `inference.py`).

This is not plainly trivial, but arguably low-effort, given that the rest of the application would remain unchanged.
You can find more details on the app design here:

https://aferro.dynu.net/research_engineering/sound_event_detection_demo/

I'm closing the issue, but feel free to reopen if you want to propose any contributions to this end.
Cheers!  
Andres
